name: main
on: [ push, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10, 11, 12, 13, 14, 15 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run static type checking
        run: yarn type-check
      - name: Run unit tests
        run: yarn test --forceExit # Jest won't exit in Node 15 for whatever reason
      - name: Collect coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
