language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  APP_ENV: testing
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_DRIVER: sync
  DB_CONNECTION: sqlite
  APP_KEY: 16efa6c23c2e8c705826b0e66778fbe7
  ADMIN_EMAIL: koel@example.com
  ADMIN_NAME: Koel
  ADMIN_PASSWORD: SoSecureK0el
  LASTFM_API_KEY: foo
  LASTFM_API_SECRET: bar

cache:
  - npm
  - composer

branches:
  only:
    - master

cache:
  - npm
  - composer

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - npm install -g npm@latest
  - npm install

script: 
  - phpunit
  - npm test
