name: CI

on:
  push:
    branches: 
    - master
    - actions

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Composer
      run: composer install --no-interaction
    - name: PHPUnit
      run: composer coverage
